#!/bin/sh
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"
runApplication blockMesh
runApplication checkMesh
rm -rf 0
cp -r 0.orig 0
runApplication setFields
runApplication $(getApplication)
