"""
build_arm.py
============
Generate a high-fidelity MJCF model of a 3-DOF (RRR) manipulator whose link
inertials come from `inertia.py` rather than from guesses or auto-derived
primitives.

Kinematics
----------
    joint 1  (q1) : yaw   about world +z   at the top of a fixed pedestal
    joint 2  (q2) : pitch about +y         (shoulder)
    joint 3  (q3) : pitch about +y         (elbow)
A payload mass is rigidly attached at the forearm tip.

Each body frame origin sits at its proximal joint, so link COMs and inertias
computed in `inertia.py` drop in without further transformation.

The generated file also declares:
  * per-joint damping and dry friction (frictionloss), the physical parameters
    that Project 1's system-identification pipeline recovers,
  * `motor` (direct-torque) actuators with a single shared gain that stands in
    for the motor torque constant,
so the same model serves both the modelling and the identification stories.

Run `python src/build_arm.py` to (re)write models/arm3.xml.
"""

from __future__ import annotations

import os
import numpy as np

from inertia import (MATERIAL_DENSITY, hollow_cylinder_link, solid_sphere,
                     MassProperties)


# --- Design parameters (what a CAD model would fix) ------------------------
RHO = MATERIAL_DENSITY["aluminium_6061"]
PEDESTAL_H = 0.10          # fixed base height, m
L1 = 0.15                  # shoulder riser length, m
L2 = 0.30                  # upper arm length, m
L3 = 0.25                  # forearm length, m
PAYLOAD_MASS = 0.50        # tip payload, kg
PAYLOAD_R = 0.03           # payload radius, m

# --- "True" physical parameters that identification will try to recover ----
# (damping [N m s/rad], frictionloss [N m]) per joint, plus a motor gain.
TRUE_DAMPING = np.array([0.50, 0.40, 0.20])
TRUE_FRICTIONLOSS = np.array([0.30, 0.25, 0.15])
TRUE_MOTOR_GAIN = 0.85     # real motor delivers 85% of nominal torque


def _inertial_tag(mp: MassProperties, indent: str) -> str:
    fi = mp.fullinertia()
    c = mp.com
    return (f'{indent}<inertial pos="{c[0]:.6f} {c[1]:.6f} {c[2]:.6f}" '
            f'mass="{mp.mass:.6f}" '
            f'fullinertia="{fi[0]:.6e} {fi[1]:.6e} {fi[2]:.6e} '
            f'{fi[3]:.6e} {fi[4]:.6e} {fi[5]:.6e}"/>')


def build_xml() -> str:
    link1 = hollow_cylinder_link([0, 0, 0], [0, 0, L1], 0.025, 0.004, RHO)
    link2 = hollow_cylinder_link([0, 0, 0], [L2, 0, 0], 0.020, 0.003, RHO)
    link3 = hollow_cylinder_link([0, 0, 0], [L3, 0, 0], 0.018, 0.003, RHO)
    payload = solid_sphere(PAYLOAD_MASS, PAYLOAD_R)

    d = TRUE_DAMPING
    f = TRUE_FRICTIONLOSS
    g = TRUE_MOTOR_GAIN

    xml = f"""<mujoco model="arm3_highfidelity">
  <!-- Generated by build_arm.py. Inertials are analytic (see inertia.py),
       not auto-derived. Edit the design parameters in build_arm.py, not here. -->
  <compiler angle="radian" autolimits="true"/>
  <option timestep="0.001" integrator="RK4" gravity="0 0 -9.81"/>

  <default>
    <geom rgba="0.7 0.72 0.75 1" contype="0" conaffinity="0"/>
    <joint type="hinge" limited="false"/>
    <motor ctrlrange="-40 40" gear="{g:.4f}"/>
  </default>

  <worldbody>
    <light pos="0 0 2.5" dir="0 0 -1" diffuse="0.9 0.9 0.9"/>
    <geom name="floor" type="plane" size="2 2 0.1" rgba="0.25 0.26 0.28 1"/>

    <!-- fixed pedestal -->
    <geom name="pedestal" type="cylinder" fromto="0 0 0 0 0 {PEDESTAL_H}"
          size="0.05" rgba="0.35 0.36 0.38 1"/>

    <body name="link1" pos="0 0 {PEDESTAL_H}">
      <joint name="q1" axis="0 0 1" damping="{d[0]:.4f}" frictionloss="{f[0]:.4f}"/>
{_inertial_tag(link1, "      ")}
      <geom name="g_link1" type="cylinder" fromto="0 0 0 0 0 {L1}" size="0.025"/>

      <body name="link2" pos="0 0 {L1}">
        <joint name="q2" axis="0 1 0" damping="{d[1]:.4f}" frictionloss="{f[1]:.4f}"/>
{_inertial_tag(link2, "        ")}
        <geom name="g_link2" type="cylinder" fromto="0 0 0 {L2} 0 0" size="0.020"/>

        <body name="link3" pos="{L2} 0 0">
          <joint name="q3" axis="0 1 0" damping="{d[2]:.4f}" frictionloss="{f[2]:.4f}"/>
{_inertial_tag(link3, "          ")}
          <geom name="g_link3" type="cylinder" fromto="0 0 0 {L3} 0 0" size="0.018"/>

          <body name="payload" pos="{L3} 0 0">
{_inertial_tag(payload, "            ")}
            <geom name="g_payload" type="sphere" size="{PAYLOAD_R}"
                  rgba="0.85 0.45 0.2 1"/>
            <site name="tip" pos="0 0 0" size="0.008"/>
          </body>
        </body>
      </body>
    </body>
  </worldbody>

  <actuator>
    <motor name="m1" joint="q1"/>
    <motor name="m2" joint="q2"/>
    <motor name="m3" joint="q3"/>
  </actuator>

  <sensor>
    <jointpos joint="q1"/>
    <jointpos joint="q2"/>
    <jointpos joint="q3"/>
  </sensor>
</mujoco>
"""
    return xml


def main() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "models", "arm3.xml")
    xml = build_xml()
    with open(out, "w") as fh:
        fh.write(xml)

    # Validate by loading in MuJoCo.
    import mujoco
    model = mujoco.MjModel.from_xml_path(out)
    print(f"wrote {out}")
    print(f"model loads: {model.nq} DoF, {model.nu} actuators, "
          f"{model.nbody} bodies")
    print(f"total mass (incl. fixed base geoms): "
          f"{sum(model.body_mass):.4f} kg")


if __name__ == "__main__":
    main()
